
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ISTAD-M1
#          issuer-uri: "http://localhost:8080/realms/A01-M1
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/db_elearning-m1
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwer
  application:
    name: elearning-a01-m1
server:
  port: 8081
